[project]
name = "weed-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autoevals>=0.2.0",
    "braintrust>=0.22.1",
    "chromadb>=1.5.9",
    "fastapi>=0.136.3",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "langchain-core>=1.4.0",
    "langchain-openai>=1.2.2",
    "numpy>=2.4.6",
    "openai>=2.38.0",
    "pandas>=3.0.3",
    "pymupdf>=1.27.2.3",
    "pypdf>=6.12.2",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.48.0",
]
